import React, { useState } from 'react';
import { Download, FileText, Code, Link, Copy, CheckCircle, Presentation, ExternalLink } from 'lucide-react';
import { ReviewReport } from '../../types';

interface ExportReportProps {
  report: ReviewReport;
}

export function ExportReport({ report }: ExportReportProps) {
  const [copiedLink, setCopiedLink] = useState(false);
  const [activeTab, setActiveTab] = useState<'markdown' | 'json' | 'client'>('markdown');

  // Generate Markdown text representation of the audit
  const generateMarkdown = () => {
    return `# UI/UX Design System Audit: ${report.title}
Platform: ${report.platform}
Date: ${new Date(report.timestamp).toLocaleDateString()}
Overall Design Rating: ${report.scores.overall.score}/100

## Executive Summary
${report.executiveSummary}

## AI Scores Breakdown
- Overall: ${report.scores.overall.score}/100 (Why: ${report.scores.overall.why})
- User Experience: ${report.scores.ux.score}/100 (Why: ${report.scores.ux.why})
- Visual UI: ${report.scores.ui.score}/100 (Why: ${report.scores.ui.why})
- Accessibility: ${report.scores.accessibility.score}/100 (Why: ${report.scores.accessibility.why})
- Conversion Metric: ${report.scores.conversion.score}/100 (Why: ${report.scores.conversion.why})

## Top Actionable Recommendations
${report.suggestions.map((s, idx) => `
### ${idx + 1}. [Severity: ${s.severity.toUpperCase()}] ${s.issue}
- **Heuristic/Principle**: ${s.heuristic}
- **Problem**: ${s.reason}
- **Business/UX Impact**: ${s.impact}
- **Actionable Fix**: ${s.fix}
- **Expected Improvement**: ${s.expectedImprovement}
`).join('\n')}

## Color Optimization Analysis
${report.colorAnalysis.palette.map((c) => `- **${c.name}**: Optimized from ${c.originalHex} to ${c.optimizedHex}. Rationale: ${c.reason}`).join('\n')}

---
Generated by DesignReview AI - The ultimate SaaS AI Design Critic.
`;
  };

  const copyToClipboard = (text: string, isLink = false) => {
    navigator.clipboard.writeText(text);
    if (isLink) {
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    } else {
      alert('Content copied to clipboard successfully!');
    }
  };

  const downloadFile = (content: string, fileName: string, contentType: string) => {
    const a = document.createElement("a");
    const file = new Blob([content], { type: contentType });
    a.href = URL.createObjectURL(file);
    a.download = fileName;
    a.click();
  };

  const shareUrl = `${window.location.origin}/share/report-${report.id}`;

  return (
    <div id="export-report-container" className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h3 className="text-sm font-bold text-black">Audit Export Center</h3>
          <p className="text-xs text-gray-500 font-medium">Extract high-fidelity reports in markdown, client slides, or structural JSON schemas.</p>
        </div>
        
        {/* Share buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={() => copyToClipboard(shareUrl, true)}
            className="flex items-center gap-2 px-4 py-2 bg-white border border-subtle rounded-full text-xs font-semibold text-black hover:bg-gray-50 transition-all shadow-soft"
          >
            {copiedLink ? <CheckCircle className="w-3.5 h-3.5 text-emerald-600" /> : <Link className="w-3.5 h-3.5 text-gray-550" />}
            <span>{copiedLink ? 'Link Copied!' : 'Generate Share Link'}</span>
          </button>

          <button
            onClick={() => downloadFile(generateMarkdown(), `design-audit-${report.id}.md`, 'text/markdown')}
            className="flex items-center gap-2 px-4 py-2 bg-black text-white rounded-full text-xs font-semibold hover:bg-zinc-800 transition-all shadow-soft"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download MD</span>
          </button>
        </div>
      </div>

      {/* Export Tabs */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Interactive Workspace (Left 2/3) */}
        <div className="lg:col-span-2 bg-white border border-subtle rounded-3xl shadow-soft flex flex-col h-[480px] overflow-hidden">
          <div className="flex items-center justify-between px-5 py-3 bg-gray-50 border-b border-subtle">
            <div className="flex items-center gap-1.5 bg-white p-0.5 border border-subtle rounded-full shadow-soft">
              <button
                onClick={() => setActiveTab('markdown')}
                className={`px-3 py-1.5 text-[10px] font-semibold rounded-full transition-all flex items-center gap-1.5 ${
                  activeTab === 'markdown' ? 'bg-black text-white shadow-soft' : 'text-gray-500 hover:text-black'
                }`}
              >
                <FileText className="w-3 h-3" />
                <span>Markdown (GitHub/Notion)</span>
              </button>
              <button
                onClick={() => setActiveTab('json')}
                className={`px-3 py-1.5 text-[10px] font-semibold rounded-full transition-all flex items-center gap-1.5 ${
                  activeTab === 'json' ? 'bg-black text-white shadow-soft' : 'text-gray-500 hover:text-black'
                }`}
              >
                <Code className="w-3 h-3" />
                <span>JSON Schema</span>
              </button>
              <button
                onClick={() => setActiveTab('client')}
                className={`px-3 py-1.5 text-[10px] font-semibold rounded-full transition-all flex items-center gap-1.5 ${
                  activeTab === 'client' ? 'bg-black text-white shadow-soft' : 'text-gray-500 hover:text-black'
                }`}
              >
                <Presentation className="w-3 h-3" />
                <span>Client Presentation</span>
              </button>
            </div>

            <button
              onClick={() => copyToClipboard(activeTab === 'markdown' ? generateMarkdown() : JSON.stringify(report, null, 2))}
              className="text-gray-500 hover:text-black flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-tight"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>Copy Raw</span>
            </button>
          </div>

          <div className="flex-1 p-6 overflow-auto bg-gray-50/10 font-mono text-xs text-gray-750 leading-normal">
            {activeTab === 'markdown' && (
              <pre className="whitespace-pre-wrap font-sans text-xs leading-relaxed max-w-3xl text-gray-700">
                {generateMarkdown()}
              </pre>
            )}

            {activeTab === 'json' && (
              <pre className="whitespace-pre text-[10px] leading-relaxed text-gray-650 font-mono">
                {JSON.stringify(report, null, 2)}
              </pre>
            )}

            {activeTab === 'client' && (
              <div className="font-sans space-y-6 max-w-2xl py-2">
                <div className="bg-black text-white rounded-3xl p-6 shadow-soft space-y-4">
                  <span className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block">Slide 1: Executive Summary</span>
                  <h3 className="text-xl font-bold tracking-tight">{report.title}</h3>
                  <p className="text-xs text-gray-300 leading-relaxed">{report.executiveSummary}</p>
                </div>

                {report.suggestions.slice(0, 3).map((s, idx) => (
                  <div key={idx} className="bg-white border border-subtle rounded-3xl p-6 shadow-soft space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-[9px] font-bold text-gray-400 uppercase tracking-widest block">Slide {idx + 2}: Finding & Resolution</span>
                      <span className="text-[10px] font-semibold text-rose-600 bg-rose-50 px-2 py-0.5 rounded-full border border-rose-200 capitalize">
                        {s.severity} Severity
                      </span>
                    </div>
                    <h4 className="text-sm font-bold text-black">{s.issue}</h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-1.5">
                        <span className="text-[9px] font-bold text-gray-400 uppercase tracking-wide block">The Friction</span>
                        <p className="text-xs text-gray-600 leading-relaxed">{s.reason}</p>
                      </div>
                      <div className="space-y-1.5">
                        <span className="text-[9px] font-bold text-gray-400 uppercase tracking-wide block">Actionable Fix</span>
                        <p className="text-xs text-gray-800 font-semibold leading-relaxed">{s.fix}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Client presentation checklist (Right 1/3) */}
        <div className="bg-white border border-subtle rounded-3xl p-6 space-y-4 shadow-soft">
          <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Auditor Checklist</span>
          
          <div className="space-y-4 text-xs">
            <div className="flex items-start gap-3">
              <div className="w-5 h-5 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0 mt-0.5 font-bold">✓</div>
              <div className="space-y-0.5">
                <span className="font-bold text-black block">Multimodal Screenshot Scanned</span>
                <p className="text-[11px] text-gray-500 leading-normal">Full layout coordinates mapping complete.</p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-5 h-5 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0 mt-0.5 font-bold">✓</div>
              <div className="space-y-0.5">
                <span className="font-bold text-black block">Accessibility Verified</span>
                <p className="text-[11px] text-gray-500 leading-normal">WCAG 1.4.3 minimum AA requirements validated.</p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <div className="w-5 h-5 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0 mt-0.5 font-bold">✓</div>
              <div className="space-y-0.5">
                <span className="font-bold text-black block">Psychology Rules Applied</span>
                <p className="text-[11px] text-gray-500 leading-normal">Fitts, Hick, Miller, and Jakob law compliance calculated.</p>
              </div>
            </div>
          </div>

          <div className="border-t border-subtle pt-4 space-y-2">
            <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Presentation Guidance</span>
            <p className="text-[11px] text-gray-500 leading-relaxed font-medium">
              When presenting to clients or senior product managers, lead with the **Executive Summary** and emphasize the **conversion/business impact** of resolving accessibility errors. Show the **Before/After slider** to visually demonstrate changes.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
